2023-02-15 12:48:03,796 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2023-02-15 12:48:04,218 - urllib3.connectionpool - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=dubai%2Cin&units=metric&appid=2dadae09d640439cd2837e7d024ee036 HTTP/1.1" 404 40
2023-02-15 12:48:04,225 - root - DEBUG - location not found "404 Client Error: Not Found for url: https://api.openweathermap.org/data/2.5/weather?q=dubai%2Cin&units=metric&appid=2dadae09d640439cd2837e7d024ee036"
2023-02-15 12:52:13,283 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2023-02-15 12:52:13,608 - urllib3.connectionpool - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=sdsd%2CUS&units=metric&appid=2dadae09d640439cd2837e7d024ee036 HTTP/1.1" 404 40
2023-02-15 12:52:13,614 - root - DEBUG - Unable to connect to api 404 Client Error: Not Found for url: https://api.openweathermap.org/data/2.5/weather?q=sdsd%2CUS&units=metric&appid=2dadae09d640439cd2837e7d024ee036
2023-02-15 12:52:13,614 - root - DEBUG - Response Text: {"cod":"404","message":"city not found"}
2023-02-15 12:52:13,615 - root - DEBUG - location not found "404 Client Error: Not Found for url: https://api.openweathermap.org/data/2.5/weather?q=sdsd%2CUS&units=metric&appid=2dadae09d640439cd2837e7d024ee036"
2023-02-21 10:34:26,108 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2023-02-21 10:34:26,440 - urllib3.connectionpool - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=minneapolis%2Cus&units=metric HTTP/1.1" 401 108
2023-02-21 10:34:26,445 - root - DEBUG - Unable to connect to api 401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=minneapolis%2Cus&units=metric
2023-02-21 10:34:26,445 - root - DEBUG - Response Text: {"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}
2023-02-21 10:34:26,445 - root - DEBUG - location not found "401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=minneapolis%2Cus&units=metric"
2023-02-21 10:35:16,943 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2023-02-21 10:35:17,243 - urllib3.connectionpool - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=in%2Cin&units=metric HTTP/1.1" 401 108
2023-02-21 10:35:17,250 - root - DEBUG - Unable to connect to api 401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=in%2Cin&units=metric
2023-02-21 10:35:17,250 - root - DEBUG - Response Text: {"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}
2023-02-21 10:35:17,251 - root - DEBUG - location not found "401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=in%2Cin&units=metric"
2023-02-21 10:35:30,130 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2023-02-21 10:35:30,335 - urllib3.connectionpool - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=Minneapolis%2Cus&units=metric HTTP/1.1" 401 108
2023-02-21 10:35:30,339 - root - DEBUG - Unable to connect to api 401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=Minneapolis%2Cus&units=metric
2023-02-21 10:35:30,339 - root - DEBUG - Response Text: {"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}
2023-02-21 10:35:30,340 - root - DEBUG - location not found "401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=Minneapolis%2Cus&units=metric"
2023-02-21 10:49:20,685 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2023-02-21 10:49:21,455 - urllib3.connectionpool - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=minneapolis%2Cus&units=metric HTTP/1.1" 401 108
2023-02-21 10:49:21,461 - root - DEBUG - Unable to connect to api 401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=minneapolis%2Cus&units=metric
2023-02-21 10:49:21,462 - root - DEBUG - Response Text: {"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}
2023-02-21 10:49:21,462 - root - DEBUG - location not found "401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=minneapolis%2Cus&units=metric"
2023-02-21 10:52:36,998 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2023-02-21 10:52:37,330 - urllib3.connectionpool - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=tokyo%2Cjp&units=metric HTTP/1.1" 401 108
2023-02-21 10:52:37,336 - root - DEBUG - Unable to connect to api 401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=tokyo%2Cjp&units=metric
2023-02-21 10:52:37,336 - root - DEBUG - Response Text: {"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}
2023-02-21 10:52:37,336 - root - DEBUG - location not found "401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=tokyo%2Cjp&units=metric"
2023-02-21 12:32:10,233 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2023-02-21 12:32:10,711 - urllib3.connectionpool - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=minneapolis%2Cus&units=metric HTTP/1.1" 401 108
2023-02-21 12:32:10,717 - root - DEBUG - Unable to connect to api 401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=minneapolis%2Cus&units=metric
2023-02-21 12:32:10,717 - root - DEBUG - Response Text: {"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}
2023-02-21 12:32:10,717 - root - DEBUG - location not found "401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=minneapolis%2Cus&units=metric"
2023-02-21 12:32:56,768 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2023-02-21 12:32:57,096 - urllib3.connectionpool - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=dallas%2Cus&units=metric HTTP/1.1" 401 108
2023-02-21 12:32:57,099 - root - DEBUG - Unable to connect to api 401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=dallas%2Cus&units=metric
2023-02-21 12:32:57,099 - root - DEBUG - Response Text: {"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}
2023-02-21 12:32:57,099 - root - DEBUG - location not found "401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?q=dallas%2Cus&units=metric"
2023-02-21 12:38:17,979 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2023-02-21 12:38:18,307 - urllib3.connectionpool - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=minneapolis%2Cus&units=metric&appid=2dadae09d640439cd2837e7d024ee036 HTTP/1.1" 200 487
